openapi: 3.0.0
info:
  version: 3.0.0
  title: FFAStrans REST API Version 3.0
  
servers:
  - url: /
  - url: /api/json/v2

paths:
  /hello:
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelloWorldResponse"
        default:
          description: Error
          content:  # Response body
            application/json:  # Media type
              schema:          # Must-have
                type: object   # Data 
                properties: 
                  id:
                    type: integer
                  name:
                    type: string
                  fullTime: 
                    type: boolean
                example:       # Sample data
                    id: 1
                    name: Jessica Right
                    fullTime: true
  /about:
    x-swagger-router-controller: about
    get:
      description: Gets ffastrans about
      operationId: about
      responses:
        "200":
          description: Success
        default:
          description: Error
    post:
      description: "Save about section. Can only save a single section and number of existing keys must match new keys"
      operationId: about_post
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: {"general": {}}
      responses:
          "200":
            description: Success
          default:
            description: Error
  /getjoblog:
    x-swagger-router-controller: get_job_log
    get:
      description: Gets an existing jobs log file contents
      operationId: get_job_log
      parameters:
        - name: jobid
          in: query
          description: A JobId, currently all branches of a job share the same jobid,
            getjoblog cannot determine which log line belongs to which branch
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
        default:
          description: Error
  /review:
    x-swagger-router-controller: review
    get:
      description: Gets review queue
      operationId: review
      responses:
        "200":
          description: Success
        default:
          description: Error
    delete:
      description: Deletes tickets from review queue
      parameters:
        - name: filename
          in: query
          description: File in review queue folder 
          required: true
          schema:
            type: string
      operationId: review_delete
      responses:
        "200":
          description: Success
        default:
          description: Error
  /tickets:
    x-swagger-router-controller: tickets
    get:
      description: Gets active and pending jobs
      parameters:
        - name: nodetails
          in: query
          description: Reduces performance impact on database significally, only returns currently active jobid's. Excluded incoming (those are complex to get)
          required: false
          schema:
            type: boolean
      operationId: tickets
      responses:
        "200":
          description: List of Jobs
        default:
          description: Error
  /machines:
    x-swagger-router-controller: machines
    get:
      description: Gets List of Farm Machines
      operationId: machines
      responses:
        "200":
          description: Success
        default:
          description: Error
    post:
      description: "Save about section"
      operationId: machines_post
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: {"ip_address": ""}
      responses:
        "200":
          description: List of Machines and config
        default:
          description: Error   
    delete:
      description: Deletes machine by name. 
      parameters:
        - name: name
          in: query
          description: Machine name to delete 
          required: true
          schema:
            type: string
      operationId: machines_delete
      responses:
        "200":
          description: Success
        default:
          description: Error
  /presets:
    x-swagger-router-controller: presets
    get:
      description: Gets List of presets
      operationId: presets
      responses:
        "200":
          description: Success
        default:
          description: Error
    post:
      description: "Post a new preset"
      operationId: presets_post
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: {"ip_address": ""}
      responses:
        "200":
          description: List of Machines and config
        default:
          description: Error   
    delete:
      description: Deletes presets by id. 
      parameters:
        - name: name
          in: query
          description: Machine name to delete 
          required: true
          schema:
            type: string
      operationId: presets_delete
      responses:
        "200":
          description: Success
        default:
          description: Error
  /metrics:
    x-swagger-router-controller: metrics
    get:
      description: Gets Prometheus compatible Farm metrics
      operationId: metrics
      responses:
        "200":
          description: List of metrics
        default:
          description: Error 
  /getjobdetails:
    x-swagger-router-controller: get_job_details
    get:
      description: Get all available details about an existing job
      operationId: get_job_details
      parameters:
        - name: jobid
          in: query
          description: A JobId, currently all branches of a job share the same jobid,
            getjoblog cannot determine which log line belongs to which branch
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
        default:
          description: Error
  /getmediainfo:
    x-swagger-router-controller: get_mediainfo
    get:
      description: Get mediainfo about a file 
      operationId: get_mediainfo
      parameters:
        - name: filepath
          in: query
          description: The path to a file from perspective of the API server
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
        default:
          description: Error

  /workflows:
    x-swagger-router-controller: workflows
    get:
      description: ""
      operationId: workflows
      parameters:
        - name: id
          in: query
          description: Workflow ID, if not  specified returns all
          # problem of the old ffastrans api: parameters as part of url (not get params but url) must be required but ffastrans has optional params
          required: false
          schema:
            type: string
        - name: nodetails
          in: query
          description: Reduces performance impact significally, surpress variables and status
          required: false
          schema:
            type: boolean
      responses:
        "200":
          description: Success
        default:
          description: Error
    post:
      description: "Import Workflow"
      operationId: workflow_post
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
              example: {"workflows": []}
      responses:
        "200":
          description: Success
        default:
          description: Error
    put:
      description: "Updates or inserts part of a workflow json"
      operationId: workflow_put
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: {"wf_id": "abcde","update":{"field":"content"}}
      responses:
        "200":
          description: Success
        default:
          description: Error
  /variables:
    x-swagger-router-controller: variables
    get:
      description: ""
      operationId: variables
      responses:
        "200":
          description: Success
        default:
          description: Error
    delete:
      description: Deletes a variable
      operationId: variables_delete
      parameters:
        - name: name
          in: query
          description: Name of the variable to be deleted
          required: true
          schema:
            type: string
      
      responses:
        "200":
          description: Success
        default:
          description: Error
    post:
      description: "Create/Update Variable"
      operationId: variables_post
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
              example: {"name":"s_example","data":"Example Description/Value"}
      responses:
        "200":
          description: Success
        default:
          description: Error
  /jobs:
    x-swagger-router-controller: jobs
    post:
      description: ""
      operationId: jobs
      parameters:
        - name: jobid
          in: query
          description: A JobId, currently all branches of a job share the same jobid,
            getjoblog cannot determine which log line belongs to which branch
          required: true
          schema:
            type: string

      requestBody:
        content:
          application/json:
            schema:      # Request body contents
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
              example: {"wf_id":"<workflow id>","inputfile":"<full path to file>","start_proc":"<processor node id>","variables":[{"name":"<s_string>","data":"<string>"},{"name":"<i_string>","data":"<integer>"},{"name":"<f_string>","data":"<number>"}]}
      responses:
        "200":
          description: Success
        default:
          description: Error
    
    put:
      description: "value is job prio for priority and milliseconds for pause if you want auto-resume or resume with delay. job is job_id for already running jobs or full path to incoming file"
      operationId: jobs_put
      requestBody:
        content:
          application/json:
            schema:      # Request body contents
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
              example: {"action": "pause resume abort priority","job": "","split_id": "","value":5}
      responses:
        "200":
          description: Success
        default:
          description: Error
    get:
      description: "List of Job Splits (branches)"
      operationId: jobs_get
      parameters:
        - name: start
          in: query
          description: "for paged output"
          required: false
          schema:
            type: string
        - name: count
          in: query
          description: "for paged output"
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Success
        default:
          description: Error 
  /api/json/v2/jobs:
    x-swagger-router-controller: jobs_v2
    get:
      description: "DEPRECATED, use /jobs"
      operationId: jobs_v2
      parameters:
        - name: start
          in: query
          description: "for paged output"
          required: false
          schema:
            type: string
        - name: count
          in: query
          description: "for paged output"
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Success
        default:
          description: Error 
  /api/json/v2/workflows/{id}:
    x-swagger-router-controller: workflows
    get:
      description: "DEPRECATED Legacy API call (use /workflows). If /id is not specified returns all. ID is marked as required because the standard requires path parameters to be required but this API it also works without /id parameter"
      operationId: workflows_v2
      parameters:
        - name: id
          in: path
          description: "optional (even if marked as required)"
          # problem of the old ffastrans api: parameters as part of url (not get params but url) must be required by standard but ffastrans has optional params
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
        default:
          description: Error

  /swagger:
    x-swagger-pipe: swagger_raw


components:
  schemas:
    HelloWorldResponse:
      required:
        - message
      properties:
        message:
          type: string
    ErrorResponse:
      required:
        - message
      properties:
        message:
          type: string