{
 "title": "FFAStrans Running",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Active Jobs By Workflow",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (wf_name)(rate(ffas_running_job{}[30s]))"
    }
   ]
  },
  {
   "title": "Branch Run Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    { "expr": "ffas_running_job" }
   ]
  },
  {
   "title": "Queued Jobs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ffas_jobs_queue_count[15s])"
    }
   ]
  },
  {
   "title": "FFAStrans Running Jobs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "ffas_jobs_running_count" }
   ]
  }
 ]
}